name: Build portfolio report

on:
  schedule:
    - cron: "*/5 * * * *"   # run every 5 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-portfolio
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        run: |
          python generate.py
          mkdir -p docs
          cp report.html docs/index.html

      - name: Commit updated report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git diff --cached --quiet || git commit -m "Update report [skip ci]"
          git push
