name: Build portfolio report

on:
  schedule:
    - cron: "0 * * * *"   # run every hour
  workflow_dispatch:       # manual run button

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney   # so timestamps are in your local time
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        run: |
          python v_3.0_patched.py
          mkdir -p docs
          cp report.html docs/index.html

      - name: Commit updated report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git diff --cached --quiet || git commit -m "Update report [skip ci]"
          git push
